import type {
  StudentActivity,
  StudentProfile,
  University,
  UniversityFilterState,
} from './types';

const activity = (
  title: string,
  impact: string,
  tier: StudentActivity['tier'],
): StudentActivity => ({ title, impact, tier });

const buildApplicationSteps = (schoolName: string, portfolioHint?: string) => [
  'Step 1: Check program fit and intake availability.',
  'Step 2: Verify academic and language requirements for your chosen major.',
  'Step 3: Prepare transcripts, passport, and financial planning documents.',
  'Step 4: Draft essays with school-specific examples and goals.',
  'Step 5: Request recommendation letters early so teachers have time to personalize them.',
  `Step 6: Submit the ${schoolName} admission application before the main deadline.`,
  'Step 7: Apply for scholarships, aid, or honors options as soon as the portal opens.',
  `Step 8: Track interview, offer, visa, and next actions in your application checklist.${portfolioHint ? ` ${portfolioHint}` : ''}`,
];

const buildScholarshipSteps = (schoolName: string) => [
  `Step 1: Review which ${schoolName} scholarships are automatic versus separate applications.`,
  'Step 2: Confirm the GPA, English, leadership, and need-based criteria for each award.',
  'Step 3: Prepare a concise achievement summary with evidence links or certificates.',
  'Step 4: Tailor your essay to the scholarship theme instead of reusing the admission essay.',
  'Step 5: Ask recommenders to mention leadership, initiative, and measurable impact.',
  'Step 6: Submit the scholarship form before the priority deadline whenever possible.',
  'Step 7: Track extra interview, honors, or portfolio requests after submission.',
  'Step 8: Follow up on missing documents and keep your profile updates ready for appeal or reconsideration.',
];

const sharedTips = [
  'Improve your English score if you are just under the scholarship target.',
  'Show depth in one or two activities instead of listing too many shallow activities.',
  'Use measurable outcomes in essays and resumes.',
  'Apply before the priority deadline to access more merit funding.',
  'Ask recommenders to explain your growth, reliability, and initiative with examples.',
];

export const studentProfiles: StudentProfile[] = [
  {
    id: 'linh-stem',
    label: 'STEM climber',
    name: 'Linh Tran',
    headline: 'Strong STEM student with a clear scholarship need and good upward momentum.',
    gpa10: 8.4,
    classRankPercent: 9,
    academicStanding: 'Top 10%',
    standardizedTests: {
      SAT: 1380,
      AP: 3,
      'National Exam': 8.6,
    },
    englishProficiency: {
      exam: 'IELTS',
      score: 6.5,
    },
    intendedMajor: 'Computer Science',
    countryPreferences: ['Canada', 'Australia', 'Netherlands', 'USA'],
    budgetPerYearUsd: 32000,
    extracurricularActivities: [
      activity('School coding club', 'Led weekly algorithm sessions for 35 students.', 'school'),
      activity('Robotics team', 'Built a line-tracing robot for a regional showcase.', 'regional'),
      activity('Youth climate data hackathon', 'Developed a data dashboard prototype.', 'national'),
    ],
    awards: [
      activity('Provincial informatics silver medal', 'Placed in the top 12 statewide.', 'regional'),
      activity('Top 10 national STEM hackathon', 'Won with a student analytics prototype.', 'national'),
    ],
    leadershipExperience: [
      activity('Coding club president', 'Grew club membership from 18 to 35 students.', 'school'),
    ],
    volunteerImpact: [
      activity('STEM for girls workshop', 'Mentored 20 middle-school students in basic coding.', 'regional'),
    ],
    researchProjects: [
      activity('Air-quality sensor project', 'Built a small IoT dashboard and presented findings to teachers.', 'school'),
    ],
    financialNeed: 'high',
    citizenship: 'Vietnam',
    residency: 'International applicant',
    preferredIntakeTerm: 'Fall 2026',
    preferredScholarshipTypes: ['merit', 'need-based', 'tuition reduction', 'automatic scholarship'],
  },
  {
    id: 'minh-business',
    label: 'Budget-first strategist',
    name: 'Minh Nguyen',
    headline: 'Business-focused student with practical leadership and a tighter budget ceiling.',
    gpa10: 7.8,
    classRankPercent: 18,
    academicStanding: 'Top 25%',
    standardizedTests: {
      SAT: 1260,
      'National Exam': 8.1,
    },
    englishProficiency: {
      exam: 'Unknown',
    },
    intendedMajor: 'Business Analytics',
    countryPreferences: ['Malaysia', 'Netherlands', 'Germany', 'South Korea'],
    budgetPerYearUsd: 20000,
    extracurricularActivities: [
      activity('Student business club', 'Organized a school-wide startup pitch day.', 'school'),
      activity('Part-time family business support', 'Managed social media and inventory reporting.', 'school'),
    ],
    awards: [
      activity('School entrepreneurship challenge winner', 'Won first prize with a recycling app idea.', 'school'),
    ],
    leadershipExperience: [
      activity('Class vice president', 'Coordinated fundraising and club events.', 'school'),
    ],
    volunteerImpact: [
      activity('Community library fundraiser', 'Raised books and tutoring support for 60 students.', 'school'),
    ],
    researchProjects: [],
    financialNeed: 'medium',
    citizenship: 'Vietnam',
    residency: 'International applicant',
    preferredIntakeTerm: 'Fall 2026',
    preferredScholarshipTypes: ['tuition reduction', 'automatic scholarship', 'honors'],
  },
  {
    id: 'an-creative',
    label: 'Creative communicator',
    name: 'An Pham',
    headline: 'Communications student with strong leadership, portfolio work, and balanced academics.',
    gpa10: 8.1,
    classRankPercent: 13,
    academicStanding: 'Top 15%',
    standardizedTests: {
      SAT: 1310,
      AP: 2,
    },
    englishProficiency: {
      exam: 'Duolingo',
      score: 125,
    },
    intendedMajor: 'Media and Communication',
    countryPreferences: ['Australia', 'China', 'Hong Kong', 'New Zealand'],
    budgetPerYearUsd: 27000,
    extracurricularActivities: [
      activity('School podcast host', 'Produced 18 student-life episodes with 2,000+ plays.', 'school'),
      activity('Youth journalism camp', 'Published a feature on local education access.', 'regional'),
      activity('Design volunteer collective', 'Created social content for two non-profits.', 'regional'),
    ],
    awards: [
      activity('Regional public speaking finalist', 'Reached the final round among 80 students.', 'regional'),
    ],
    leadershipExperience: [
      activity('Media club founder', 'Built a 12-person editorial team and content calendar.', 'school'),
      activity('School event MC', 'Led live hosting for the annual community fair.', 'school'),
    ],
    volunteerImpact: [
      activity('Community mental-health campaign', 'Managed story collection and awareness posts.', 'regional'),
    ],
    researchProjects: [
      activity('Digital storytelling portfolio', 'Curated writing, video, and campaign case studies.', 'school'),
    ],
    financialNeed: 'medium',
    citizenship: 'Vietnam',
    residency: 'International applicant',
    preferredIntakeTerm: 'Fall 2026',
    preferredScholarshipTypes: ['merit', 'honors', 'tuition reduction'],
  },
];

export const defaultProfileId = studentProfiles[0].id;

export const defaultUniversityFilters: UniversityFilterState = {
  search: '',
  country: 'all',
  major: 'all',
  budget: null,
  scholarshipType: 'all',
  eligibility: 'all',
  fitLevel: 'all',
  englishRequirement: 'all',
  sortBy: 'best-fit',
};

export const universityCatalogue: University[] = [
  {
    id: 'asu',
    name: 'Arizona State University',
    country: 'USA',
    city: 'Tempe',
    reputationLabel: 'Innovation-focused public university',
    rankingTier: 'Strong international',
    tuitionRangeUsd: { min: 32000, max: 36500 },
    livingCostRangeUsd: { min: 15500, max: 18500 },
    availableMajors: ['Computer Science', 'Business Analytics', 'Journalism', 'Data Science', 'Graphic Design'],
    majorClusters: ['technology', 'business', 'media', 'design'],
    minimumAcademicRequirements: {
      minGpa10: 7.4,
      targetGpa10: 8.3,
      maxClassRankPercent: 25,
      academicStandingNotes: 'A strong upward trend helps for selective majors.',
      extracurricularDepthTarget: 2,
      awardsTarget: 1,
      leadershipTarget: 1,
      volunteerTarget: 1,
      researchPortfolioPreferred: false,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.0, target: 6.5 },
      { exam: 'TOEFL', minimum: 61, target: 80 },
      { exam: 'Duolingo', minimum: 95, target: 110 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'optional', target: 1250 },
      { exam: 'ACT', policy: 'optional', target: 26 },
      { exam: 'AP', policy: 'recommended', target: 2 },
    ],
    scholarships: [
      {
        id: 'asu-new-american',
        name: 'New American University Scholarship',
        type: 'automatic scholarship',
        automatic: true,
        coverage: 'Up to 14,500 USD tuition reduction',
        estimatedValueUsd: 14500,
        benefits: ['Tuition reduction', 'Renewable for four years'],
        minimumGpa10: 8.0,
        targetGpa10: 8.6,
        englishThresholds: { IELTS: 6.5, TOEFL: 80, Duolingo: 115 },
        leadershipPreferred: 1,
        awardsPreferred: 1,
        notes: 'Best offers usually go to students with clear academic strength and strong engagement.',
        applicationSteps: buildScholarshipSteps('Arizona State University'),
      },
      {
        id: 'asu-honors',
        name: 'Barrett Honors College Scholarship',
        type: 'honors',
        automatic: false,
        coverage: '5,000 USD honors funding',
        estimatedValueUsd: 5000,
        benefits: ['Honors seminars', 'Priority advising', 'Community housing'],
        minimumGpa10: 8.4,
        targetGpa10: 8.8,
        englishThresholds: { IELTS: 6.5, TOEFL: 88, Duolingo: 120 },
        leadershipPreferred: 1,
        awardsPreferred: 1,
        notes: 'Essay quality matters a lot for Barrett selection.',
        applicationSteps: buildScholarshipSteps('Arizona State University'),
      },
    ],
    automaticMeritScholarships: ['New American University Scholarship'],
    needBasedAidAvailability: false,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-06-01',
      priorityDeadline: '2026-01-15',
      scholarshipDeadline: '2026-02-01',
    },
    documentRequirements: ['Academic transcripts', 'Passport copy', 'Financial statement', 'Resume/activity list'],
    essayRequirements: {
      required: false,
      summary: 'Optional essays improve scholarship positioning and honors review.',
    },
    recommendationLettersRequired: 1,
    interviewRequirement: 'not required',
    portfolioRequirement: 'recommended',
    specialNotes: ['Computer Science fills quickly, so earlier applications are safer.', 'Barrett honors works best for students who can show initiative beyond grades.'],
    officialApplicationSteps: buildApplicationSteps('Arizona State University', 'Portfolio uploads help for design programs.'),
    scholarshipApplicationSteps: buildScholarshipSteps('Arizona State University'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'If you are near the scholarship line, lifting IELTS from 6.5 to 7.0 meaningfully strengthens merit consideration.',
    ],
    benefits: ['Large internship ecosystem', 'Innovation labs', 'Optional honors pathway'],
    scholarshipHighlights: ['Automatic merit review for strong students', 'Honors funding with separate essay'],
  },
  {
    id: 'melbourne',
    name: 'University of Melbourne',
    country: 'Australia',
    city: 'Melbourne',
    reputationLabel: 'Global research-intensive university',
    rankingTier: 'Global elite',
    tuitionRangeUsd: { min: 31500, max: 44000 },
    livingCostRangeUsd: { min: 18000, max: 22500 },
    availableMajors: ['Computer Science', 'Commerce', 'Biomedical Science', 'Media and Communication', 'Architecture'],
    majorClusters: ['technology', 'business', 'science', 'media', 'design'],
    minimumAcademicRequirements: {
      minGpa10: 8.2,
      targetGpa10: 8.8,
      maxClassRankPercent: 15,
      academicStandingNotes: 'Selective programs prefer top academic standing and evidence of academic rigor.',
      extracurricularDepthTarget: 2,
      awardsTarget: 1,
      leadershipTarget: 1,
      volunteerTarget: 1,
      researchPortfolioPreferred: true,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.5, target: 7.0 },
      { exam: 'TOEFL', minimum: 79, target: 94 },
      { exam: 'Duolingo', minimum: 120, target: 130 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'optional', target: 1400 },
      { exam: 'IB', policy: 'recommended', target: 34 },
      { exam: 'A-Level', policy: 'recommended', target: 3 },
    ],
    scholarships: [
      {
        id: 'melb-international-undergrad',
        name: 'Melbourne International Undergraduate Scholarship',
        type: 'merit',
        automatic: true,
        coverage: '10,000 USD first-year fee remission',
        estimatedValueUsd: 10000,
        benefits: ['Tuition reduction', 'Automatic consideration'],
        minimumGpa10: 8.5,
        targetGpa10: 9.0,
        englishThresholds: { IELTS: 6.5, TOEFL: 88, Duolingo: 125 },
        awardsPreferred: 1,
        notes: 'The strongest offers usually go to students near the top of their class.',
        applicationSteps: buildScholarshipSteps('University of Melbourne'),
      },
      {
        id: 'melb-chancellors',
        name: 'Narrm Chancellor Scholarship',
        type: 'full ride',
        automatic: false,
        coverage: 'Full tuition plus living stipend',
        estimatedValueUsd: 52000,
        benefits: ['Full tuition', 'Living stipend', 'Accommodation support', 'Leadership program'],
        minimumGpa10: 8.9,
        targetGpa10: 9.3,
        englishThresholds: { IELTS: 7.0, TOEFL: 94, Duolingo: 130 },
        leadershipPreferred: 2,
        awardsPreferred: 2,
        researchPreferred: true,
        notes: 'Aspirational but exceptional for students with top academics and standout impact.',
        applicationSteps: buildScholarshipSteps('University of Melbourne'),
      },
    ],
    automaticMeritScholarships: ['Melbourne International Undergraduate Scholarship'],
    needBasedAidAvailability: false,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-05-31',
      priorityDeadline: '2026-03-31',
      scholarshipDeadline: '2026-04-15',
    },
    documentRequirements: ['Academic transcripts', 'English score report', 'Passport copy', 'CV/achievement summary'],
    essayRequirements: {
      required: true,
      summary: 'One personal statement focused on academic intent and contribution.',
    },
    recommendationLettersRequired: 2,
    interviewRequirement: 'possible',
    portfolioRequirement: 'recommended',
    specialNotes: ['Architecture and design pathways may request a portfolio review.', 'Strong essays matter more when academics are close to the threshold.'],
    officialApplicationSteps: buildApplicationSteps('University of Melbourne', 'Creative applicants should prepare a clean digital portfolio link.'),
    scholarshipApplicationSteps: buildScholarshipSteps('University of Melbourne'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'Use your essay to explain why Melbourne’s curriculum structure fits your goals, not just why you want to study abroad.',
    ],
    benefits: ['Global reputation', 'Research access', 'Strong alumni network'],
    scholarshipHighlights: ['Automatic merit remission', 'Prestigious full-tuition leadership scholarships'],
  },
  {
    id: 'ubco',
    name: 'University of British Columbia Okanagan',
    country: 'Canada',
    city: 'Kelowna',
    reputationLabel: 'Research university with supportive campus scale',
    rankingTier: 'Strong international',
    tuitionRangeUsd: { min: 28500, max: 39200 },
    livingCostRangeUsd: { min: 15000, max: 18200 },
    availableMajors: ['Computer Science', 'Data Science', 'Management', 'Media Studies', 'Biology'],
    majorClusters: ['technology', 'business', 'media', 'science'],
    minimumAcademicRequirements: {
      minGpa10: 8.0,
      targetGpa10: 8.7,
      maxClassRankPercent: 20,
      academicStandingNotes: 'Competitive majors prefer stronger math preparation.',
      extracurricularDepthTarget: 2,
      awardsTarget: 1,
      leadershipTarget: 1,
      volunteerTarget: 1,
      researchPortfolioPreferred: false,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.5, target: 7.0 },
      { exam: 'TOEFL', minimum: 90, target: 96 },
      { exam: 'Duolingo', minimum: 125, target: 130 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'optional', target: 1320 },
      { exam: 'ACT', policy: 'optional', target: 28 },
      { exam: 'AP', policy: 'recommended', target: 2 },
    ],
    scholarships: [
      {
        id: 'ubc-major-entrance',
        name: 'International Major Entrance Scholarship',
        type: 'merit',
        automatic: false,
        coverage: '15,000 USD merit award',
        estimatedValueUsd: 15000,
        benefits: ['Tuition reduction', 'Renewable with strong GPA'],
        minimumGpa10: 8.6,
        targetGpa10: 9.0,
        englishThresholds: { IELTS: 6.5, TOEFL: 92, Duolingo: 128 },
        leadershipPreferred: 1,
        awardsPreferred: 1,
        volunteerPreferred: 1,
        notes: 'The committee values initiative, service, and future contribution to campus.',
        applicationSteps: buildScholarshipSteps('UBC Okanagan'),
      },
      {
        id: 'ubc-outstanding-intl',
        name: 'Outstanding International Student Award',
        type: 'tuition reduction',
        automatic: true,
        coverage: '10,000 USD entrance award',
        estimatedValueUsd: 10000,
        benefits: ['Tuition reduction', 'Automatic review'],
        minimumGpa10: 8.2,
        targetGpa10: 8.8,
        englishThresholds: { IELTS: 6.5, TOEFL: 90, Duolingo: 125 },
        awardsPreferred: 1,
        notes: 'Automatic review, but stronger English scores help scholarship ranking.',
        applicationSteps: buildScholarshipSteps('UBC Okanagan'),
      },
    ],
    automaticMeritScholarships: ['Outstanding International Student Award'],
    needBasedAidAvailability: false,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-01-15',
      priorityDeadline: '2025-12-01',
      scholarshipDeadline: '2025-12-01',
    },
    documentRequirements: ['Academic transcripts', 'English score report', 'Personal profile responses'],
    essayRequirements: {
      required: true,
      summary: 'Short personal profile prompts focused on initiative, collaboration, and impact.',
    },
    recommendationLettersRequired: 2,
    interviewRequirement: 'possible',
    portfolioRequirement: 'not required',
    specialNotes: ['Kelowna campus can be a stronger fit for students who want a more personal environment.', 'Personal profile quality matters for scholarships.'],
    officialApplicationSteps: buildApplicationSteps('UBC Okanagan'),
    scholarshipApplicationSteps: buildScholarshipSteps('UBC Okanagan'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'Use recommendation letters to validate leadership and service, not just classroom performance.',
    ],
    benefits: ['Co-op opportunities', 'Smaller campus support', 'Strong research access'],
    scholarshipHighlights: ['Automatic entrance award', 'Competitive merit scholarship via personal profile'],
  },
  {
    id: 'twente',
    name: 'University of Twente',
    country: 'Netherlands',
    city: 'Enschede',
    reputationLabel: 'Project-based technical and interdisciplinary learning',
    rankingTier: 'Strong international',
    tuitionRangeUsd: { min: 15000, max: 19000 },
    livingCostRangeUsd: { min: 12000, max: 14800 },
    availableMajors: ['Computer Science', 'Business Information Technology', 'Industrial Design', 'Communication Science', 'Electrical Engineering'],
    majorClusters: ['technology', 'business', 'design', 'media'],
    minimumAcademicRequirements: {
      minGpa10: 7.8,
      targetGpa10: 8.5,
      maxClassRankPercent: 25,
      academicStandingNotes: 'Project readiness and motivation matter alongside grades.',
      extracurricularDepthTarget: 2,
      awardsTarget: 0,
      leadershipTarget: 1,
      volunteerTarget: 0,
      researchPortfolioPreferred: false,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.5, target: 7.0 },
      { exam: 'TOEFL', minimum: 90, target: 95 },
      { exam: 'Duolingo', minimum: 120, target: 125 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'not-required' },
      { exam: 'AP', policy: 'recommended', target: 2 },
      { exam: 'National Exam', policy: 'required', minimum: 7.5, target: 8.2 },
    ],
    scholarships: [
      {
        id: 'twente-holland',
        name: 'Holland Scholarship',
        type: 'tuition reduction',
        automatic: false,
        coverage: '5,000 USD first-year award',
        estimatedValueUsd: 5000,
        benefits: ['First-year tuition reduction'],
        minimumGpa10: 8.0,
        targetGpa10: 8.6,
        englishThresholds: { IELTS: 6.5, TOEFL: 90, Duolingo: 120 },
        leadershipPreferred: 1,
        notes: 'A clear reason for choosing the Netherlands strengthens the application.',
        applicationSteps: buildScholarshipSteps('University of Twente'),
      },
      {
        id: 'twente-kipaji',
        name: 'Kipaji Scholarship',
        type: 'merit',
        automatic: false,
        coverage: '12,000 USD across the first year',
        estimatedValueUsd: 12000,
        benefits: ['Tuition reduction', 'Mentorship support'],
        minimumGpa10: 8.5,
        targetGpa10: 8.9,
        englishThresholds: { IELTS: 7.0, TOEFL: 95, Duolingo: 125 },
        leadershipPreferred: 1,
        awardsPreferred: 1,
        notes: 'Best suited for students who can explain academic direction and initiative.',
        applicationSteps: buildScholarshipSteps('University of Twente'),
      },
    ],
    automaticMeritScholarships: [],
    needBasedAidAvailability: false,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-05-01',
      priorityDeadline: '2026-02-01',
      scholarshipDeadline: '2026-02-01',
    },
    documentRequirements: ['Academic transcripts', 'CV', 'Passport', 'Motivation letter'],
    essayRequirements: {
      required: true,
      summary: 'Motivation letter should explain project-based learning fit.',
    },
    recommendationLettersRequired: 1,
    interviewRequirement: 'possible',
    portfolioRequirement: 'recommended',
    specialNotes: ['Communication Science and design pathways value examples of practical work.', 'Dutch universities care about fit and self-direction.'],
    officialApplicationSteps: buildApplicationSteps('University of Twente'),
    scholarshipApplicationSteps: buildScholarshipSteps('University of Twente'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'Show evidence that you enjoy hands-on teamwork, not only exam performance.',
    ],
    benefits: ['Strong project-based curriculum', 'Lower overall cost than many anglophone options'],
    scholarshipHighlights: ['Good value baseline cost', 'Competitive first-year scholarships'],
  },
  {
    id: 'monash-malaysia',
    name: 'Monash University Malaysia',
    country: 'Malaysia',
    city: 'Subang Jaya',
    reputationLabel: 'Australian degree with lower regional cost',
    rankingTier: 'Accessible value',
    tuitionRangeUsd: { min: 12500, max: 17000 },
    livingCostRangeUsd: { min: 8000, max: 10200 },
    availableMajors: ['Computer Science', 'Business Analytics', 'Psychology', 'Communication', 'Data Science'],
    majorClusters: ['technology', 'business', 'media', 'science'],
    minimumAcademicRequirements: {
      minGpa10: 7.2,
      targetGpa10: 8.1,
      maxClassRankPercent: 30,
      academicStandingNotes: 'A practical option for students balancing quality and affordability.',
      extracurricularDepthTarget: 1,
      awardsTarget: 0,
      leadershipTarget: 0,
      volunteerTarget: 0,
      researchPortfolioPreferred: false,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.0, target: 6.5 },
      { exam: 'TOEFL', minimum: 69, target: 79 },
      { exam: 'Duolingo', minimum: 105, target: 115 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'optional', target: 1200 },
      { exam: 'National Exam', policy: 'required', minimum: 7.0, target: 7.8 },
    ],
    scholarships: [
      {
        id: 'monash-excellence',
        name: 'Monash High Achiever Award',
        type: 'automatic scholarship',
        automatic: true,
        coverage: '25% tuition reduction',
        estimatedValueUsd: 4000,
        benefits: ['Tuition reduction', 'Automatic review'],
        minimumGpa10: 8.0,
        targetGpa10: 8.6,
        englishThresholds: { IELTS: 6.5, TOEFL: 79, Duolingo: 115 },
        notes: 'A straightforward merit option for strong but budget-conscious applicants.',
        applicationSteps: buildScholarshipSteps('Monash University Malaysia'),
      },
      {
        id: 'monash-leadership',
        name: 'Future Leaders Scholarship',
        type: 'honors',
        automatic: false,
        coverage: '35% tuition reduction plus leadership program',
        estimatedValueUsd: 5800,
        benefits: ['Tuition reduction', 'Leadership mentoring', 'Priority workshops'],
        minimumGpa10: 8.2,
        targetGpa10: 8.8,
        leadershipPreferred: 1,
        volunteerPreferred: 1,
        notes: 'Leadership narrative matters more than pure test performance.',
        applicationSteps: buildScholarshipSteps('Monash University Malaysia'),
      },
    ],
    automaticMeritScholarships: ['Monash High Achiever Award'],
    needBasedAidAvailability: false,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-07-15',
      priorityDeadline: '2026-04-30',
      scholarshipDeadline: '2026-05-15',
    },
    documentRequirements: ['Academic transcripts', 'Passport', 'English score report if available'],
    essayRequirements: {
      required: false,
      summary: 'Essays are mostly needed for the leadership scholarship route.',
    },
    recommendationLettersRequired: 1,
    interviewRequirement: 'possible',
    portfolioRequirement: 'not required',
    specialNotes: ['This is a strong value option for students who want a recognized international brand.', 'You can stay competitive without very high SAT scores.'],
    officialApplicationSteps: buildApplicationSteps('Monash University Malaysia'),
    scholarshipApplicationSteps: buildScholarshipSteps('Monash University Malaysia'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'If your English score is still pending, schedule it quickly because affordability depends on scholarship timing.',
    ],
    benefits: ['Lower living cost', 'Australian degree structure', 'Regional internship access'],
    scholarshipHighlights: ['Automatic tuition reduction', 'Leadership-focused scholarship'],
  },
  {
    id: 'auckland',
    name: 'University of Auckland',
    country: 'New Zealand',
    city: 'Auckland',
    reputationLabel: 'Leading New Zealand university with broad majors',
    rankingTier: 'Strong international',
    tuitionRangeUsd: { min: 26000, max: 35000 },
    livingCostRangeUsd: { min: 14500, max: 17500 },
    availableMajors: ['Computer Science', 'Business Analytics', 'Media and Communication', 'Biomedical Science', 'Architecture'],
    majorClusters: ['technology', 'business', 'media', 'science', 'design'],
    minimumAcademicRequirements: {
      minGpa10: 7.8,
      targetGpa10: 8.5,
      maxClassRankPercent: 20,
      academicStandingNotes: 'Students with clearer specialization and stronger English stand out.',
      extracurricularDepthTarget: 2,
      awardsTarget: 1,
      leadershipTarget: 1,
      volunteerTarget: 1,
      researchPortfolioPreferred: true,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.0, target: 6.5 },
      { exam: 'TOEFL', minimum: 80, target: 90 },
      { exam: 'Duolingo', minimum: 110, target: 120 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'optional', target: 1280 },
      { exam: 'ACT', policy: 'optional', target: 27 },
      { exam: 'National Exam', policy: 'required', minimum: 7.5, target: 8.3 },
    ],
    scholarships: [
      {
        id: 'auckland-intl-student',
        name: 'International Student Excellence Scholarship',
        type: 'merit',
        automatic: false,
        coverage: '6,000 USD tuition reduction',
        estimatedValueUsd: 6000,
        benefits: ['Tuition reduction', 'Recognition award'],
        minimumGpa10: 8.2,
        targetGpa10: 8.7,
        englishThresholds: { IELTS: 6.5, TOEFL: 90, Duolingo: 120 },
        leadershipPreferred: 1,
        awardsPreferred: 1,
        notes: 'Students with a polished statement and coherent goals perform best.',
        applicationSteps: buildScholarshipSteps('University of Auckland'),
      },
      {
        id: 'auckland-top-achiever',
        name: 'Top Achiever Scholarship',
        type: 'honors',
        automatic: false,
        coverage: '10,000 USD support plus honors network',
        estimatedValueUsd: 10000,
        benefits: ['Tuition reduction', 'Leadership program', 'Peer cohort'],
        minimumGpa10: 8.5,
        targetGpa10: 9.0,
        leadershipPreferred: 2,
        volunteerPreferred: 1,
        notes: 'Leadership and service can significantly strengthen this application.',
        applicationSteps: buildScholarshipSteps('University of Auckland'),
      },
    ],
    automaticMeritScholarships: [],
    needBasedAidAvailability: false,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-06-30',
      priorityDeadline: '2026-04-01',
      scholarshipDeadline: '2026-04-01',
    },
    documentRequirements: ['Academic transcripts', 'English score report', 'Personal statement', 'Passport'],
    essayRequirements: {
      required: true,
      summary: 'One statement focused on academic intent and contribution to campus.',
    },
    recommendationLettersRequired: 1,
    interviewRequirement: 'possible',
    portfolioRequirement: 'recommended',
    specialNotes: ['Creative programs may ask for portfolio samples even when the main university form does not.', 'Budget planning matters because scholarship amounts rarely cover the full cost.'],
    officialApplicationSteps: buildApplicationSteps('University of Auckland'),
    scholarshipApplicationSteps: buildScholarshipSteps('University of Auckland'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'If you are close academically, a sharper personal statement can make a bigger difference than a slightly higher SAT.',
    ],
    benefits: ['Strong regional reputation', 'Broad subject choice', 'Supportive student services'],
    scholarshipHighlights: ['Excellence scholarship', 'Leadership-oriented top achiever route'],
  },
  {
    id: 'constructor',
    name: 'Constructor University Bremen',
    country: 'Germany',
    city: 'Bremen',
    reputationLabel: 'English-taught, scholarship-heavy private campus',
    rankingTier: 'Accessible value',
    tuitionRangeUsd: { min: 22000, max: 28000 },
    livingCostRangeUsd: { min: 11000, max: 13200 },
    availableMajors: ['Computer Science', 'Data Science', 'International Business', 'Integrated Social Sciences', 'Psychology'],
    majorClusters: ['technology', 'business', 'media', 'science'],
    minimumAcademicRequirements: {
      minGpa10: 7.5,
      targetGpa10: 8.3,
      maxClassRankPercent: 30,
      academicStandingNotes: 'The university is flexible academically but scholarship competition is steeper.',
      extracurricularDepthTarget: 1,
      awardsTarget: 0,
      leadershipTarget: 1,
      volunteerTarget: 0,
      researchPortfolioPreferred: false,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.5, target: 7.0 },
      { exam: 'TOEFL', minimum: 90, target: 95 },
      { exam: 'Duolingo', minimum: 115, target: 120 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'optional', target: 1250 },
      { exam: 'ACT', policy: 'optional', target: 26 },
      { exam: 'National Exam', policy: 'required', minimum: 7.3, target: 8.0 },
    ],
    scholarships: [
      {
        id: 'constructor-tuition',
        name: 'Academic Achievement Scholarship',
        type: 'tuition reduction',
        automatic: true,
        coverage: '10,000 USD tuition reduction',
        estimatedValueUsd: 10000,
        benefits: ['Tuition reduction', 'Automatic review'],
        minimumGpa10: 8.0,
        targetGpa10: 8.6,
        englishThresholds: { IELTS: 6.5, TOEFL: 90, Duolingo: 115 },
        notes: 'This can materially lower total cost for students already near the academic target.',
        applicationSteps: buildScholarshipSteps('Constructor University Bremen'),
      },
      {
        id: 'constructor-need',
        name: 'Global Access Grant',
        type: 'need-based',
        automatic: false,
        coverage: 'Up to 14,000 USD combined tuition support',
        estimatedValueUsd: 14000,
        benefits: ['Need-based grant', 'Payment flexibility'],
        minimumGpa10: 7.8,
        targetGpa10: 8.3,
        financialNeedEligible: ['medium', 'high'],
        englishThresholds: { IELTS: 6.5, TOEFL: 90, Duolingo: 115 },
        notes: 'Strong fit for students who can document need and maintain a solid academic baseline.',
        applicationSteps: buildScholarshipSteps('Constructor University Bremen'),
      },
    ],
    automaticMeritScholarships: ['Academic Achievement Scholarship'],
    needBasedAidAvailability: true,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-07-01',
      priorityDeadline: '2026-03-01',
      scholarshipDeadline: '2026-03-15',
    },
    documentRequirements: ['Academic transcripts', 'Motivation letter', 'Proof of finances', 'English score report'],
    essayRequirements: {
      required: true,
      summary: 'Motivation letter should explain why an interdisciplinary campus suits your goals.',
    },
    recommendationLettersRequired: 1,
    interviewRequirement: 'possible',
    portfolioRequirement: 'not required',
    specialNotes: ['Need-based grants make this school more realistic for budget-sensitive students.', 'Strong English is useful because coursework is fully English-taught.'],
    officialApplicationSteps: buildApplicationSteps('Constructor University Bremen'),
    scholarshipApplicationSteps: buildScholarshipSteps('Constructor University Bremen'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'If budget is the main concern, prepare need documentation early because scholarship review can run in parallel with admission.',
    ],
    benefits: ['English-taught campus', 'Scholarship-friendly pricing', 'Close-knit academic advising'],
    scholarshipHighlights: ['Automatic academic reduction', 'Real need-based support for internationals'],
  },
  {
    id: 'kaist',
    name: 'KAIST',
    country: 'South Korea',
    city: 'Daejeon',
    reputationLabel: 'Elite STEM-focused research university',
    rankingTier: 'Highly selective',
    tuitionRangeUsd: { min: 7000, max: 9000 },
    livingCostRangeUsd: { min: 9000, max: 11800 },
    availableMajors: ['Computer Science', 'Electrical Engineering', 'Bioengineering', 'Industrial Design', 'Data Science'],
    majorClusters: ['technology', 'science', 'design'],
    minimumAcademicRequirements: {
      minGpa10: 8.6,
      targetGpa10: 9.1,
      maxClassRankPercent: 10,
      academicStandingNotes: 'KAIST is an ambitious target unless you already have standout academics.',
      extracurricularDepthTarget: 2,
      awardsTarget: 1,
      leadershipTarget: 1,
      volunteerTarget: 0,
      researchPortfolioPreferred: true,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.5, target: 7.0 },
      { exam: 'TOEFL', minimum: 83, target: 95 },
      { exam: 'Duolingo', minimum: 115, target: 125 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'recommended', target: 1450 },
      { exam: 'ACT', policy: 'recommended', target: 32 },
      { exam: 'AP', policy: 'recommended', target: 4 },
    ],
    scholarships: [
      {
        id: 'kaist-international',
        name: 'KAIST International Student Scholarship',
        type: 'full ride',
        automatic: true,
        coverage: 'Full tuition plus monthly stipend',
        estimatedValueUsd: 18000,
        benefits: ['Full tuition', 'Monthly stipend', 'National health insurance support'],
        minimumGpa10: 8.8,
        targetGpa10: 9.2,
        englishThresholds: { IELTS: 6.5, TOEFL: 90, Duolingo: 120 },
        researchPreferred: true,
        awardsPreferred: 1,
        notes: 'Scholarship is generous, but selection is tied to strong academic and STEM evidence.',
        applicationSteps: buildScholarshipSteps('KAIST'),
      },
      {
        id: 'kaist-honors',
        name: 'Honors Research Fellowship',
        type: 'honors',
        automatic: false,
        coverage: 'Research stipend and faculty pairing',
        estimatedValueUsd: 4500,
        benefits: ['Research stipend', 'Lab placement', 'Faculty mentorship'],
        minimumGpa10: 9.0,
        targetGpa10: 9.3,
        researchPreferred: true,
        leadershipPreferred: 1,
        notes: 'Best fit for students with projects, Olympiad results, or strong technical portfolios.',
        applicationSteps: buildScholarshipSteps('KAIST'),
      },
    ],
    automaticMeritScholarships: ['KAIST International Student Scholarship'],
    needBasedAidAvailability: false,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-01-09',
      priorityDeadline: '2025-11-28',
      scholarshipDeadline: '2026-01-09',
    },
    documentRequirements: ['Academic transcripts', 'English score report', 'Two recommendations', 'Activity/achievement list'],
    essayRequirements: {
      required: true,
      summary: 'Short essays focused on STEM readiness, curiosity, and research motivation.',
    },
    recommendationLettersRequired: 2,
    interviewRequirement: 'possible',
    portfolioRequirement: 'recommended',
    specialNotes: ['Only a strong future target if you want STEM or design-adjacent innovation.', 'Media, business, and broad humanities are not the right fit here.'],
    officialApplicationSteps: buildApplicationSteps('KAIST', 'Students with technical projects should include a short project portfolio or GitHub links.'),
    scholarshipApplicationSteps: buildScholarshipSteps('KAIST'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'If you are applying to KAIST, strengthening your project evidence can matter as much as a small GPA increase.',
    ],
    benefits: ['Very strong value if admitted', 'Generous international scholarship support', 'Top STEM environment'],
    scholarshipHighlights: ['Full tuition plus stipend', 'Research-focused honors support'],
    hardConstraints: {
      majorsNotSupported: ['Business Analytics', 'Media and Communication', 'Journalism'],
    },
  },
  {
    id: 'hku',
    name: 'The University of Hong Kong',
    country: 'Hong Kong',
    city: 'Hong Kong',
    reputationLabel: 'Prestigious Asia hub with broad global opportunities',
    rankingTier: 'Highly selective',
    tuitionRangeUsd: { min: 22000, max: 28500 },
    livingCostRangeUsd: { min: 10500, max: 14500 },
    availableMajors: ['Computer Science', 'Economics and Finance', 'Journalism', 'Biomedical Science', 'Architecture'],
    majorClusters: ['technology', 'business', 'media', 'science', 'design'],
    minimumAcademicRequirements: {
      minGpa10: 8.3,
      targetGpa10: 8.9,
      maxClassRankPercent: 12,
      academicStandingNotes: 'HKU values strong academics and a clear international mindset.',
      extracurricularDepthTarget: 2,
      awardsTarget: 1,
      leadershipTarget: 1,
      volunteerTarget: 1,
      researchPortfolioPreferred: true,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.5, target: 7.0 },
      { exam: 'TOEFL', minimum: 93, target: 100 },
      { exam: 'Duolingo', minimum: 120, target: 130 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'recommended', target: 1400 },
      { exam: 'ACT', policy: 'recommended', target: 30 },
      { exam: 'AP', policy: 'recommended', target: 3 },
    ],
    scholarships: [
      {
        id: 'hku-entry',
        name: 'HKU Entrance Scholarship',
        type: 'merit',
        automatic: true,
        coverage: '10,000 USD to full tuition',
        estimatedValueUsd: 24000,
        benefits: ['Tuition reduction', 'Possible full tuition for top applicants'],
        minimumGpa10: 8.7,
        targetGpa10: 9.1,
        englishThresholds: { IELTS: 7.0, TOEFL: 100, Duolingo: 130 },
        awardsPreferred: 1,
        leadershipPreferred: 1,
        notes: 'Better English and stronger distinctions sharply improve scholarship range.',
        applicationSteps: buildScholarshipSteps('The University of Hong Kong'),
      },
      {
        id: 'hku-talent',
        name: 'Talent Development Scholarship',
        type: 'honors',
        automatic: false,
        coverage: '6,000 USD plus enrichment funding',
        estimatedValueUsd: 6000,
        benefits: ['Enrichment fund', 'Leadership programming'],
        minimumGpa10: 8.5,
        targetGpa10: 8.9,
        leadershipPreferred: 2,
        volunteerPreferred: 1,
        notes: 'This award favors students who can show sustained initiative and campus contribution.',
        applicationSteps: buildScholarshipSteps('The University of Hong Kong'),
      },
    ],
    automaticMeritScholarships: ['HKU Entrance Scholarship'],
    needBasedAidAvailability: false,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-08-22',
      priorityDeadline: '2026-03-15',
      scholarshipDeadline: '2026-03-15',
    },
    documentRequirements: ['Academic transcripts', 'English score report', 'Achievement list', 'Passport'],
    essayRequirements: {
      required: true,
      summary: 'Personal statement should connect your goals to HKU’s international ecosystem.',
    },
    recommendationLettersRequired: 1,
    interviewRequirement: 'possible',
    portfolioRequirement: 'recommended',
    specialNotes: ['Journalism and design-related applications benefit from portfolio-style samples.', 'Entrance awards can be significant for top scorers.'],
    officialApplicationSteps: buildApplicationSteps('The University of Hong Kong'),
    scholarshipApplicationSteps: buildScholarshipSteps('The University of Hong Kong'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'If you want merit funding here, push English beyond the minimum because that improves both readiness and scholarship odds.',
    ],
    benefits: ['Asia hub location', 'Strong exchange opportunities', 'Generous top-end merit support'],
    scholarshipHighlights: ['Automatic entrance scholarship', 'Leadership-focused enhancement funding'],
  },
  {
    id: 'dku',
    name: 'Duke Kunshan University',
    country: 'China',
    city: 'Kunshan',
    reputationLabel: 'Liberal arts model with high scholarship generosity',
    rankingTier: 'Highly selective',
    tuitionRangeUsd: { min: 32000, max: 45500 },
    livingCostRangeUsd: { min: 9000, max: 12500 },
    availableMajors: ['Data Science', 'Economics', 'Global Health', 'Media and Arts', 'Molecular Bioscience'],
    majorClusters: ['technology', 'business', 'media', 'science'],
    minimumAcademicRequirements: {
      minGpa10: 8.1,
      targetGpa10: 8.8,
      maxClassRankPercent: 15,
      academicStandingNotes: 'DKU likes students who bring both academic quality and intellectual curiosity.',
      extracurricularDepthTarget: 2,
      awardsTarget: 1,
      leadershipTarget: 1,
      volunteerTarget: 1,
      researchPortfolioPreferred: true,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.5, target: 7.0 },
      { exam: 'TOEFL', minimum: 85, target: 100 },
      { exam: 'Duolingo', minimum: 120, target: 130 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'optional', target: 1380 },
      { exam: 'ACT', policy: 'optional', target: 30 },
      { exam: 'AP', policy: 'recommended', target: 3 },
    ],
    scholarships: [
      {
        id: 'dku-need-merit',
        name: 'DKU Signature Scholarship',
        type: 'full ride',
        automatic: true,
        coverage: 'From 20% tuition reduction to full tuition',
        estimatedValueUsd: 36000,
        benefits: ['Large tuition support', 'Possible research funding'],
        minimumGpa10: 8.5,
        targetGpa10: 9.0,
        englishThresholds: { IELTS: 7.0, TOEFL: 100, Duolingo: 130 },
        leadershipPreferred: 1,
        awardsPreferred: 1,
        researchPreferred: true,
        financialNeedEligible: ['medium', 'high'],
        notes: 'This is a high-upside school if you can pair strong English with a differentiated story.',
        applicationSteps: buildScholarshipSteps('Duke Kunshan University'),
      },
      {
        id: 'dku-honors',
        name: 'Civic Leadership Grant',
        type: 'honors',
        automatic: false,
        coverage: '8,000 USD leadership and project funding',
        estimatedValueUsd: 8000,
        benefits: ['Project grant', 'Leadership program', 'Faculty mentorship'],
        minimumGpa10: 8.3,
        targetGpa10: 8.8,
        leadershipPreferred: 2,
        volunteerPreferred: 1,
        notes: 'Particularly strong for students with community initiative or storytelling projects.',
        applicationSteps: buildScholarshipSteps('Duke Kunshan University'),
      },
    ],
    automaticMeritScholarships: ['DKU Signature Scholarship'],
    needBasedAidAvailability: true,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-03-01',
      priorityDeadline: '2025-11-03',
      scholarshipDeadline: '2026-01-15',
    },
    documentRequirements: ['Academic transcripts', 'English score report', 'Student writing sample', 'Activity resume'],
    essayRequirements: {
      required: true,
      summary: 'Essays should show curiosity, purpose, and how you would use DKU’s interdisciplinary environment.',
    },
    recommendationLettersRequired: 2,
    interviewRequirement: 'possible',
    portfolioRequirement: 'recommended',
    specialNotes: ['This school can become very affordable if you are scholarship-competitive.', 'Media and Arts applicants should link portfolio or content samples.'],
    officialApplicationSteps: buildApplicationSteps('Duke Kunshan University', 'Media and Arts applicants should keep a tight, annotated portfolio ready.'),
    scholarshipApplicationSteps: buildScholarshipSteps('Duke Kunshan University'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'If you already have a strong story, improving English to 7.0 can unlock a much stronger scholarship band here.',
    ],
    benefits: ['Large scholarship upside', 'Interdisciplinary curriculum', 'Close faculty access'],
    scholarshipHighlights: ['High scholarship ceiling', 'Leadership and project-based funding'],
  },
  {
    id: 'nus',
    name: 'National University of Singapore',
    country: 'Singapore',
    city: 'Singapore',
    reputationLabel: 'Top Asian university with high academic intensity',
    rankingTier: 'Global elite',
    tuitionRangeUsd: { min: 21000, max: 31000 },
    livingCostRangeUsd: { min: 12000, max: 16000 },
    availableMajors: ['Computer Science', 'Business Analytics', 'Communications and New Media', 'Life Sciences', 'Architecture'],
    majorClusters: ['technology', 'business', 'media', 'science', 'design'],
    minimumAcademicRequirements: {
      minGpa10: 8.7,
      targetGpa10: 9.2,
      maxClassRankPercent: 8,
      academicStandingNotes: 'NUS is usually a reach unless academics are clearly top-tier.',
      extracurricularDepthTarget: 2,
      awardsTarget: 1,
      leadershipTarget: 1,
      volunteerTarget: 1,
      researchPortfolioPreferred: true,
    },
    englishRequirements: [
      { exam: 'IELTS', minimum: 6.5, target: 7.0 },
      { exam: 'TOEFL', minimum: 92, target: 100 },
      { exam: 'Duolingo', minimum: 120, target: 130 },
    ],
    standardizedPolicies: [
      { exam: 'SAT', policy: 'recommended', target: 1450 },
      { exam: 'ACT', policy: 'recommended', target: 32 },
      { exam: 'AP', policy: 'recommended', target: 4 },
    ],
    scholarships: [
      {
        id: 'nus-global-merit',
        name: 'NUS Global Merit Scholarship',
        type: 'full ride',
        automatic: false,
        coverage: 'Full tuition and living stipend',
        estimatedValueUsd: 35000,
        benefits: ['Full tuition', 'Living stipend', 'Guaranteed overseas program funding'],
        minimumGpa10: 9.0,
        targetGpa10: 9.4,
        englishThresholds: { IELTS: 7.0, TOEFL: 100, Duolingo: 130 },
        leadershipPreferred: 1,
        awardsPreferred: 2,
        researchPreferred: true,
        notes: 'This is highly ambitious and best suited to top academic performers.',
        applicationSteps: buildScholarshipSteps('National University of Singapore'),
      },
      {
        id: 'nus-admission-award',
        name: 'NUS Admission Merit Award',
        type: 'merit',
        automatic: false,
        coverage: '10,000 USD annual tuition support',
        estimatedValueUsd: 10000,
        benefits: ['Annual tuition reduction'],
        minimumGpa10: 8.8,
        targetGpa10: 9.2,
        englishThresholds: { IELTS: 7.0, TOEFL: 98, Duolingo: 125 },
        awardsPreferred: 1,
        notes: 'Strong academics remain the main driver for this award.',
        applicationSteps: buildScholarshipSteps('National University of Singapore'),
      },
    ],
    automaticMeritScholarships: [],
    needBasedAidAvailability: false,
    deadlines: {
      intake: 'Fall 2026',
      applicationDeadline: '2026-02-26',
      priorityDeadline: '2025-12-15',
      scholarshipDeadline: '2026-02-26',
    },
    documentRequirements: ['Academic transcripts', 'English score report', 'Personal statement', 'Achievement summary'],
    essayRequirements: {
      required: true,
      summary: 'A concise statement on intellectual direction and fit with your chosen faculty.',
    },
    recommendationLettersRequired: 2,
    interviewRequirement: 'possible',
    portfolioRequirement: 'recommended',
    specialNotes: ['A great aspiration school if you are already performing near the top of your cohort.', 'Scholarships are powerful but very competitive.'],
    officialApplicationSteps: buildApplicationSteps('National University of Singapore'),
    scholarshipApplicationSteps: buildScholarshipSteps('National University of Singapore'),
    tipsToIncreaseChances: [
      ...sharedTips,
      'If NUS is your reach option, use it as a benchmark for how much more academic strength you need to unlock elite scholarships.',
    ],
    benefits: ['Outstanding reputation', 'Strong Asian industry links', 'High-return scholarships for top applicants'],
    scholarshipHighlights: ['Elite full-ride scholarship', 'Merit awards for top admits'],
  },
];
