/* eslint-disable */
// Auto-generated by scripts/build-university-fit-rankings.mjs
// Sources:
// - THE World University Rankings 2026: https://www.timeshighereducation.com/world-university-rankings/latest/world-ranking
// - Webometrics Vietnam Ranking January 2026: https://www.webometrics.org/vietnam
// Generated at: 2026-04-05T12:41:42.919Z

export interface WorldRankingEntry {
  rank: number;
  name: string;
  country: string;
  overallScore: number;
  sourceUrl: string;
}

export interface VietnamRankingEntry {
  rank: number;
  worldRank: number;
  name: string;
  country: 'Vietnam';
  impactRank: number;
  opennessRank: number;
  excellenceRank: number;
  sourceUrl: string;
}

export const theWorldTop100_2026: WorldRankingEntry[] = [
  {
    "rank": 1,
    "name": "University of Oxford",
    "country": "United Kingdom",
    "overallScore": 98.2,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-oxford"
  },
  {
    "rank": 2,
    "name": "Massachusetts Institute of Technology",
    "country": "United States",
    "overallScore": 97.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/massachusetts-institute-technology"
  },
  {
    "rank": 3,
    "name": "Princeton University",
    "country": "United States",
    "overallScore": 97.2,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/princeton-university"
  },
  {
    "rank": 3,
    "name": "University of Cambridge",
    "country": "United Kingdom",
    "overallScore": 97.2,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-cambridge"
  },
  {
    "rank": 5,
    "name": "Harvard University",
    "country": "United States",
    "overallScore": 97.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/harvard-university"
  },
  {
    "rank": 5,
    "name": "Stanford University",
    "country": "United States",
    "overallScore": 97.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/stanford-university"
  },
  {
    "rank": 7,
    "name": "California Institute of Technology",
    "country": "United States",
    "overallScore": 96.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/california-institute-technology"
  },
  {
    "rank": 8,
    "name": "Imperial College London",
    "country": "United Kingdom",
    "overallScore": 94.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/imperial-college-london"
  },
  {
    "rank": 9,
    "name": "University of California, Berkeley",
    "country": "United States",
    "overallScore": 94.4,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-california-berkeley"
  },
  {
    "rank": 10,
    "name": "Yale University",
    "country": "United States",
    "overallScore": 94.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/yale-university"
  },
  {
    "rank": 11,
    "name": "ETH Zurich",
    "country": "Switzerland",
    "overallScore": 93.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/eth-zurich"
  },
  {
    "rank": 12,
    "name": "Tsinghua University",
    "country": "China",
    "overallScore": 93,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/tsinghua-university"
  },
  {
    "rank": 13,
    "name": "Peking University",
    "country": "China",
    "overallScore": 92.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/peking-university"
  },
  {
    "rank": 14,
    "name": "University of Pennsylvania",
    "country": "United States",
    "overallScore": 90.8,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-pennsylvania"
  },
  {
    "rank": 15,
    "name": "The University of Chicago",
    "country": "United States",
    "overallScore": 90.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-chicago"
  },
  {
    "rank": 16,
    "name": "Johns Hopkins University",
    "country": "United States",
    "overallScore": 90.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/johns-hopkins-university"
  },
  {
    "rank": 17,
    "name": "National University of Singapore",
    "country": "Singapore",
    "overallScore": 89.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/national-university-singapore"
  },
  {
    "rank": 18,
    "name": "Cornell University",
    "country": "United States",
    "overallScore": 89.5,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/cornell-university"
  },
  {
    "rank": 18,
    "name": "University of California, Los Angeles",
    "country": "United States",
    "overallScore": 89.5,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-california-los-angeles"
  },
  {
    "rank": 20,
    "name": "Columbia University",
    "country": "United States",
    "overallScore": 89.4,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/columbia-university"
  },
  {
    "rank": 21,
    "name": "University of Toronto",
    "country": "Canada",
    "overallScore": 88.5,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-toronto"
  },
  {
    "rank": 22,
    "name": "UCL",
    "country": "United Kingdom",
    "overallScore": 87.5,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/ucl"
  },
  {
    "rank": 23,
    "name": "University of Michigan-Ann Arbor",
    "country": "United States",
    "overallScore": 86.9,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-michigan-ann-arbor"
  },
  {
    "rank": 24,
    "name": "Carnegie Mellon University",
    "country": "United States",
    "overallScore": 85,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/carnegie-mellon-university"
  },
  {
    "rank": 25,
    "name": "University of Washington",
    "country": "United States",
    "overallScore": 83.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-washington"
  },
  {
    "rank": 26,
    "name": "The University of Tokyo",
    "country": "Japan",
    "overallScore": 83.5,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-tokyo"
  },
  {
    "rank": 27,
    "name": "Technical University of Munich",
    "country": "Germany",
    "overallScore": 83.4,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/technical-university-munich"
  },
  {
    "rank": 28,
    "name": "Duke University",
    "country": "United States",
    "overallScore": 82.9,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/duke-university"
  },
  {
    "rank": 29,
    "name": "University of Edinburgh",
    "country": "United Kingdom",
    "overallScore": 82.5,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-edinburgh"
  },
  {
    "rank": 30,
    "name": "Northwestern University",
    "country": "United States",
    "overallScore": 81.9,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/northwestern-university"
  },
  {
    "rank": 31,
    "name": "Nanyang Technological University, Singapore",
    "country": "Singapore",
    "overallScore": 81.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/nanyang-technological-university-singapore"
  },
  {
    "rank": 31,
    "name": "New York University",
    "country": "United States",
    "overallScore": 81.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/new-york-university"
  },
  {
    "rank": 33,
    "name": "University of Hong Kong",
    "country": "Hong Kong",
    "overallScore": 80.5,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-hong-kong"
  },
  {
    "rank": 34,
    "name": "LMU Munich",
    "country": "Germany",
    "overallScore": 79.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/lmu-munich"
  },
  {
    "rank": 35,
    "name": "École Polytechnique Fédérale de Lausanne",
    "country": "Switzerland",
    "overallScore": 79.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/ecole-polytechnique-federale-de-lausanne"
  },
  {
    "rank": 36,
    "name": "Fudan University",
    "country": "China",
    "overallScore": 79.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/fudan-university"
  },
  {
    "rank": 37,
    "name": "University of Melbourne",
    "country": "Australia",
    "overallScore": 79,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-melbourne"
  },
  {
    "rank": 38,
    "name": "King’s College London",
    "country": "United Kingdom",
    "overallScore": 78.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/kings-college-london"
  },
  {
    "rank": 39,
    "name": "Zhejiang University",
    "country": "China",
    "overallScore": 78.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/zhejiang-university"
  },
  {
    "rank": 40,
    "name": "Shanghai Jiao Tong University",
    "country": "China",
    "overallScore": 77.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/shanghai-jiao-tong-university"
  },
  {
    "rank": 41,
    "name": "Georgia Institute of Technology",
    "country": "United States",
    "overallScore": 77.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/georgia-institute-technology"
  },
  {
    "rank": 41,
    "name": "McGill University",
    "country": "Canada",
    "overallScore": 77.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/mcgill-university"
  },
  {
    "rank": 41,
    "name": "The Chinese University of Hong Kong",
    "country": "Hong Kong",
    "overallScore": 77.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/chinese-university-hong-kong"
  },
  {
    "rank": 41,
    "name": "University of Illinois at Urbana-Champaign",
    "country": "United States",
    "overallScore": 77.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-illinois-urbana-champaign"
  },
  {
    "rank": 45,
    "name": "University of British Columbia",
    "country": "Canada",
    "overallScore": 77,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-british-columbia"
  },
  {
    "rank": 46,
    "name": "KU Leuven",
    "country": "Belgium",
    "overallScore": 76.8,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/ku-leuven"
  },
  {
    "rank": 47,
    "name": "University of California, San Diego",
    "country": "United States",
    "overallScore": 76.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-california-san-diego"
  },
  {
    "rank": 48,
    "name": "Paris Sciences et Lettres – PSL Research University Paris",
    "country": "France",
    "overallScore": 76.5,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/paris-sciences-et-lettres-psl-research-university-paris"
  },
  {
    "rank": 49,
    "name": "Universität Heidelberg",
    "country": "Germany",
    "overallScore": 76.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/universitat-heidelberg"
  },
  {
    "rank": 50,
    "name": "University of Texas at Austin",
    "country": "United States",
    "overallScore": 75.8,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-texas-austin"
  },
  {
    "rank": 51,
    "name": "University of Science and Technology of China",
    "country": "China",
    "overallScore": 75.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-science-and-technology-china"
  },
  {
    "rank": 52,
    "name": "London School of Economics and Political Science",
    "country": "United Kingdom",
    "overallScore": 75.4,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/london-school-economics-and-political-science"
  },
  {
    "rank": 53,
    "name": "Karolinska Institute",
    "country": "Sweden",
    "overallScore": 75,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/karolinska-institute"
  },
  {
    "rank": 53,
    "name": "The University of Sydney",
    "country": "Australia",
    "overallScore": 75,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-sydney"
  },
  {
    "rank": 53,
    "name": "University of Wisconsin-Madison",
    "country": "United States",
    "overallScore": 75,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-wisconsin-madison"
  },
  {
    "rank": 56,
    "name": "University of Manchester",
    "country": "United Kingdom",
    "overallScore": 74.9,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-manchester"
  },
  {
    "rank": 57,
    "name": "Delft University of Technology",
    "country": "Netherlands",
    "overallScore": 74.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/delft-university-technology"
  },
  {
    "rank": 58,
    "name": "Monash University",
    "country": "Australia",
    "overallScore": 74.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/monash-university"
  },
  {
    "rank": 58,
    "name": "Seoul National University",
    "country": "South Korea",
    "overallScore": 74.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/seoul-national-university"
  },
  {
    "rank": 58,
    "name": "The Hong Kong University of Science and Technology",
    "country": "Hong Kong",
    "overallScore": 74.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/hong-kong-university-science-and-technology"
  },
  {
    "rank": 61,
    "name": "Kyoto University",
    "country": "Japan",
    "overallScore": 74,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/kyoto-university"
  },
  {
    "rank": 62,
    "name": "Nanjing University",
    "country": "China",
    "overallScore": 73.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/nanjing-university"
  },
  {
    "rank": 62,
    "name": "University of Amsterdam",
    "country": "Netherlands",
    "overallScore": 73.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-amsterdam"
  },
  {
    "rank": 64,
    "name": "University of California, Davis",
    "country": "United States",
    "overallScore": 72.8,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-california-davis"
  },
  {
    "rank": 65,
    "name": "Brown University",
    "country": "United States",
    "overallScore": 72.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/brown-university"
  },
  {
    "rank": 66,
    "name": "Wageningen University & Research",
    "country": "Netherlands",
    "overallScore": 72.2,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/wageningen-university-research"
  },
  {
    "rank": 67,
    "name": "Washington University in St Louis",
    "country": "United States",
    "overallScore": 72,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/washington-university-st-louis"
  },
  {
    "rank": 68,
    "name": "Institut Polytechnique de Paris",
    "country": "France",
    "overallScore": 71.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/institut-polytechnique-de-paris"
  },
  {
    "rank": 68,
    "name": "Université Paris-Saclay",
    "country": "France",
    "overallScore": 71.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/universite-paris-saclay"
  },
  {
    "rank": 70,
    "name": "Korea Advanced Institute of Science and Technology (KAIST)",
    "country": "South Korea",
    "overallScore": 71.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/korea-advanced-institute-science-and-technology-kaist"
  },
  {
    "rank": 70,
    "name": "Leiden University",
    "country": "Netherlands",
    "overallScore": 71.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/leiden-university"
  },
  {
    "rank": 72,
    "name": "University of California, Santa Barbara",
    "country": "United States",
    "overallScore": 71.2,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-california-santa-barbara"
  },
  {
    "rank": 73,
    "name": "Australian National University",
    "country": "Australia",
    "overallScore": 71.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/australian-national-university"
  },
  {
    "rank": 73,
    "name": "City University of Hong Kong",
    "country": "Hong Kong",
    "overallScore": 71.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/city-university-hong-kong"
  },
  {
    "rank": 73,
    "name": "University of Southern California",
    "country": "United States",
    "overallScore": 71.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-southern-california"
  },
  {
    "rank": 76,
    "name": "Boston University",
    "country": "United States",
    "overallScore": 70.4,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/boston-university"
  },
  {
    "rank": 76,
    "name": "Sorbonne University",
    "country": "France",
    "overallScore": 70.4,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/sorbonne-university"
  },
  {
    "rank": 78,
    "name": "University of North Carolina at Chapel Hill",
    "country": "United States",
    "overallScore": 70.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-north-carolina-chapel-hill"
  },
  {
    "rank": 79,
    "name": "UNSW Sydney",
    "country": "Australia",
    "overallScore": 70,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/unsw-sydney"
  },
  {
    "rank": 80,
    "name": "The Hong Kong Polytechnic University",
    "country": "Hong Kong",
    "overallScore": 69.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/hong-kong-polytechnic-university"
  },
  {
    "rank": 80,
    "name": "The University of Queensland",
    "country": "Australia",
    "overallScore": 69.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-queensland"
  },
  {
    "rank": 80,
    "name": "University of Bristol",
    "country": "United Kingdom",
    "overallScore": 69.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-bristol"
  },
  {
    "rank": 82,
    "name": "University of Groningen",
    "country": "Netherlands",
    "overallScore": 69.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-groningen"
  },
  {
    "rank": 84,
    "name": "University of Glasgow",
    "country": "United Kingdom",
    "overallScore": 68.9,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-glasgow"
  },
  {
    "rank": 85,
    "name": "Purdue University West Lafayette",
    "country": "United States",
    "overallScore": 68.8,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/purdue-university-west-lafayette"
  },
  {
    "rank": 86,
    "name": "Yonsei University (Seoul campus)",
    "country": "South Korea",
    "overallScore": 68.5,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/yonsei-university-seoul-campus"
  },
  {
    "rank": 87,
    "name": "Sungkyunkwan University (SKKU)",
    "country": "South Korea",
    "overallScore": 68.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/sungkyunkwan-university-skku"
  },
  {
    "rank": 88,
    "name": "University of Minnesota",
    "country": "United States",
    "overallScore": 67.5,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-minnesota"
  },
  {
    "rank": 89,
    "name": "Humboldt University of Berlin",
    "country": "Germany",
    "overallScore": 67.2,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/humboldt-university-berlin"
  },
  {
    "rank": 90,
    "name": "University of Copenhagen",
    "country": "Denmark",
    "overallScore": 67.1,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-copenhagen"
  },
  {
    "rank": 91,
    "name": "Charité - Universitätsmedizin Berlin",
    "country": "Germany",
    "overallScore": 66.9,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/charite-universitatsmedizin-berlin"
  },
  {
    "rank": 92,
    "name": "RWTH Aachen University",
    "country": "Germany",
    "overallScore": 66.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/rwth-aachen-university"
  },
  {
    "rank": 92,
    "name": "University of Bonn",
    "country": "Germany",
    "overallScore": 66.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-bonn"
  },
  {
    "rank": 92,
    "name": "Vanderbilt University",
    "country": "United States",
    "overallScore": 66.7,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/vanderbilt-university"
  },
  {
    "rank": 95,
    "name": "Lund University",
    "country": "Sweden",
    "overallScore": 66.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/lund-university"
  },
  {
    "rank": 95,
    "name": "University of Vienna",
    "country": "Austria",
    "overallScore": 66.6,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-vienna"
  },
  {
    "rank": 97,
    "name": "University of California, Irvine",
    "country": "United States",
    "overallScore": 66.4,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-california-irvine"
  },
  {
    "rank": 98,
    "name": "KTH Royal Institute of Technology",
    "country": "Sweden",
    "overallScore": 66.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/kth-royal-institute-technology"
  },
  {
    "rank": 98,
    "name": "University of Birmingham",
    "country": "United Kingdom",
    "overallScore": 66.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-birmingham"
  },
  {
    "rank": 98,
    "name": "University of Tübingen",
    "country": "Germany",
    "overallScore": 66.3,
    "sourceUrl": "https://www.timeshighereducation.com/world-university-rankings/university-tubingen"
  }
];

export const webometricsVietnamTop100_Jan2026: VietnamRankingEntry[] = [
  {
    "rank": 1,
    "worldRank": 756,
    "name": "Vietnam National University Hanoi / Đại học Quốc gia Hà Nội",
    "country": "Vietnam",
    "impactRank": 587,
    "opennessRank": 1127,
    "excellenceRank": 1178,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 2,
    "worldRank": 1070,
    "name": "Duy Tan University / Đại học Duy Tân DTU",
    "country": "Vietnam",
    "impactRank": 3244,
    "opennessRank": 1927,
    "excellenceRank": 471,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 3,
    "worldRank": 1245,
    "name": "Hanoi University of Science and Technology / Trường Đại học Bách Khoa Hà Nội",
    "country": "Vietnam",
    "impactRank": 1976,
    "opennessRank": 1498,
    "excellenceRank": 1655,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 4,
    "worldRank": 1325,
    "name": "Ton Duc Thang University / Đại học Tôn Đức Thắng Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 4659,
    "opennessRank": 2426,
    "excellenceRank": 389,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 5,
    "worldRank": 1334,
    "name": "University of Economics Ho Chi Minh City / Trường Đại học Kinh tế Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 2537,
    "opennessRank": 2233,
    "excellenceRank": 1467,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 6,
    "worldRank": 1433,
    "name": "Nguyen Tat Thanh University / Đại học Nguyễn Tất Thành NTU",
    "country": "Vietnam",
    "impactRank": 3014,
    "opennessRank": 2955,
    "excellenceRank": 1277,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 7,
    "worldRank": 1478,
    "name": "University of Danang / Đại học Đà Nẵng",
    "country": "Vietnam",
    "impactRank": 1525,
    "opennessRank": 1817,
    "excellenceRank": 2390,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 8,
    "worldRank": 1558,
    "name": "VNUHCM University of Technology / Trường Đại học Bách khoa",
    "country": "Vietnam",
    "impactRank": 3207,
    "opennessRank": 1830,
    "excellenceRank": 1725,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 9,
    "worldRank": 1979,
    "name": "Thuyloi University / Đại học Thủy lợi",
    "country": "Vietnam",
    "impactRank": 1390,
    "opennessRank": 4182,
    "excellenceRank": 2850,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 10,
    "worldRank": 1999,
    "name": "Can Tho University / Đại học Cần Thơ",
    "country": "Vietnam",
    "impactRank": 3750,
    "opennessRank": 2097,
    "excellenceRank": 2356,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 11,
    "worldRank": 2302,
    "name": "Hue University / Đại học Huế",
    "country": "Vietnam",
    "impactRank": 4892,
    "opennessRank": 2139,
    "excellenceRank": 2428,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 12,
    "worldRank": 2338,
    "name": "Ho Chi Minh City University of Industry / Đại học Công nghiệp Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 5425,
    "opennessRank": 2299,
    "excellenceRank": 2207,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 13,
    "worldRank": 2457,
    "name": "Ho Chi Minh City University of Technology HUTECH/ Đại học Công Nghệ Thành phố Hồ Chí Minh HUTECH",
    "country": "Vietnam",
    "impactRank": 6326,
    "opennessRank": 3895,
    "excellenceRank": 1558,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 14,
    "worldRank": 2544,
    "name": "Vietnam National University Ho Chi Minh City / Đại học Quốc gia Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 5074,
    "opennessRank": 18663,
    "excellenceRank": 916,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 15,
    "worldRank": 2786,
    "name": "RMIT University Vietnam",
    "country": "Vietnam",
    "impactRank": 4750,
    "opennessRank": 2716,
    "excellenceRank": 3297,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 16,
    "worldRank": 2915,
    "name": "VNUHCM International University / Trường Đại học Quốc tế",
    "country": "Vietnam",
    "impactRank": 6248,
    "opennessRank": 2746,
    "excellenceRank": 2825,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 17,
    "worldRank": 3107,
    "name": "Thai Nguyen University of Technology / Trường Đại học Kĩ thuật Công nghiệp Thái Nguyên",
    "country": "Vietnam",
    "impactRank": 3685,
    "opennessRank": 4199,
    "excellenceRank": 4014,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 18,
    "worldRank": 3136,
    "name": "Hanoi National University of Pedagogy / Trường Đại học Sư Phạm Hà Nội",
    "country": "Vietnam",
    "impactRank": 1894,
    "opennessRank": 25230,
    "excellenceRank": 3593,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 19,
    "worldRank": 3212,
    "name": "University of Economics and Law / Trường Đại Học Kinh Tế và Luật",
    "country": "Vietnam",
    "impactRank": 3284,
    "opennessRank": 5690,
    "excellenceRank": 3989,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 20,
    "worldRank": 3223,
    "name": "Vietnam National University of Agriculture",
    "country": "Vietnam",
    "impactRank": 6913,
    "opennessRank": 2535,
    "excellenceRank": 3165,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 21,
    "worldRank": 3252,
    "name": "University of Engineering and Technology / Trường Đại học Công nghệ",
    "country": "Vietnam",
    "impactRank": 2744,
    "opennessRank": 11849,
    "excellenceRank": 3415,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 22,
    "worldRank": 3266,
    "name": "Hanoi Medical University / Trường Đại học Y Hà Nội",
    "country": "Vietnam",
    "impactRank": 6938,
    "opennessRank": 4744,
    "excellenceRank": 2612,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 23,
    "worldRank": 3292,
    "name": "FPT University / Đại học FPT",
    "country": "Vietnam",
    "impactRank": 3412,
    "opennessRank": 15678,
    "excellenceRank": 3172,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 24,
    "worldRank": 3455,
    "name": "Posts and Telecommunications Institute of Technology / Học viện Công nghệ Bưu chính Viễn thông",
    "country": "Vietnam",
    "impactRank": 4462,
    "opennessRank": 4323,
    "excellenceRank": 4222,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 25,
    "worldRank": 3472,
    "name": "VNUHCM University of Science",
    "country": "Vietnam",
    "impactRank": 5663,
    "opennessRank": 27670,
    "excellenceRank": 2403,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 26,
    "worldRank": 3544,
    "name": "National Economics University / Trường Đại học Kinh tế Quốc dân",
    "country": "Vietnam",
    "impactRank": 4623,
    "opennessRank": 27756,
    "excellenceRank": 3044,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 27,
    "worldRank": 3770,
    "name": "Van Lang University / Đại học Văn Lang",
    "country": "Vietnam",
    "impactRank": 11017,
    "opennessRank": 2844,
    "excellenceRank": 2110,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 28,
    "worldRank": 3801,
    "name": "Western University Hanoi / Đại học Thành Tây Hà Nội",
    "country": "Vietnam",
    "impactRank": 11328,
    "opennessRank": 2204,
    "excellenceRank": 2200,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 29,
    "worldRank": 3839,
    "name": "Ho Chi Minh City University of Technology and Education / Đại học Sư phạm Kỹ thuật Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 6561,
    "opennessRank": 11706,
    "excellenceRank": 2681,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 30,
    "worldRank": 3871,
    "name": "Hanoi University of Mining and Geology / Trường Đại học Mỏ Địa chất",
    "country": "Vietnam",
    "impactRank": 8589,
    "opennessRank": 3867,
    "excellenceRank": 3176,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 31,
    "worldRank": 3932,
    "name": "Vinh University / Đại học Vinh",
    "country": "Vietnam",
    "impactRank": 8624,
    "opennessRank": 4596,
    "excellenceRank": 3079,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 32,
    "worldRank": 4025,
    "name": "Hanoi University of Civil Engineering / Trường Đại học Xây Dựng",
    "country": "Vietnam",
    "impactRank": 8689,
    "opennessRank": 3176,
    "excellenceRank": 3571,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 33,
    "worldRank": 4086,
    "name": "VNUHCM University of Information Technology / Trường Đại học Công Nghệ Thông Tin",
    "country": "Vietnam",
    "impactRank": 7006,
    "opennessRank": 3955,
    "excellenceRank": 4279,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 34,
    "worldRank": 4213,
    "name": "Banking University Ho Chi Minh City / Trường Đại học Ngân hàng Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 6888,
    "opennessRank": 5517,
    "excellenceRank": 4122,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 35,
    "worldRank": 4245,
    "name": "VNU Hanoi University of Science / Trường Đại học Khoa học Tự nhiên",
    "country": "Vietnam",
    "impactRank": 9420,
    "opennessRank": 23769,
    "excellenceRank": 2000,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 36,
    "worldRank": 4262,
    "name": "Can Tho University of Medicine and Pharmacy",
    "country": "Vietnam",
    "impactRank": 2637,
    "opennessRank": 982,
    "excellenceRank": 29590,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 37,
    "worldRank": 4306,
    "name": "Vietnam Academy of Science and Technology / Viện Hàn lâm Khoa học và Công nghệ Việt Nam",
    "country": "Vietnam",
    "impactRank": 10805,
    "opennessRank": 22111,
    "excellenceRank": 1428,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 38,
    "worldRank": 4366,
    "name": "Hanoi School of Public Health / Trường Đại học Y tế Công cộng",
    "country": "Vietnam",
    "impactRank": 5347,
    "opennessRank": 7991,
    "excellenceRank": 4415,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 39,
    "worldRank": 4376,
    "name": "Thu Dau Mot University / Trường Đại Học Thủ Dầu Một",
    "country": "Vietnam",
    "impactRank": 11443,
    "opennessRank": 4391,
    "excellenceRank": 2535,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 40,
    "worldRank": 4523,
    "name": "Quy Nhon University / Đại học Quy Nhơn",
    "country": "Vietnam",
    "impactRank": 7824,
    "opennessRank": 4243,
    "excellenceRank": 4570,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 41,
    "worldRank": 4547,
    "name": "VNUHCM University of Social Sciences and Humanities / Trường Đại học Khoa học Xã hội và Nhân văn",
    "country": "Vietnam",
    "impactRank": 4899,
    "opennessRank": 6398,
    "excellenceRank": 5411,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 42,
    "worldRank": 4684,
    "name": "Foreign Trade University / Trường Đại học Ngoại Thương",
    "country": "Vietnam",
    "impactRank": 1698,
    "opennessRank": 5412,
    "excellenceRank": 19004,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 43,
    "worldRank": 4743,
    "name": "Nông Lâm University / Đại học Nông lâm Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 5510,
    "opennessRank": 3714,
    "excellenceRank": 6216,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 44,
    "worldRank": 4812,
    "name": "Hanoi University of Industry / Đại học Công Nghiệp Hà Nội",
    "country": "Vietnam",
    "impactRank": 8561,
    "opennessRank": 9150,
    "excellenceRank": 3387,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 45,
    "worldRank": 4818,
    "name": "Tra Vinh University / Trường Đại học Trà Vinh",
    "country": "Vietnam",
    "impactRank": 2669,
    "opennessRank": 4422,
    "excellenceRank": 22216,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 46,
    "worldRank": 4861,
    "name": "EVN University of Electricity / Đại học Điện lực EVN",
    "country": "Vietnam",
    "impactRank": 3760,
    "opennessRank": 5846,
    "excellenceRank": 6696,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 47,
    "worldRank": 5108,
    "name": "An Giang University / Đại học An Giang",
    "country": "Vietnam",
    "impactRank": 7826,
    "opennessRank": 5724,
    "excellenceRank": 5026,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 48,
    "worldRank": 5206,
    "name": "Thai Nguyen University of Agriculture and Forestry / Trường đại học Nông Lâm Thái Nguyên",
    "country": "Vietnam",
    "impactRank": 4261,
    "opennessRank": 5979,
    "excellenceRank": 6850,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 49,
    "worldRank": 5328,
    "name": "Dong Thap University / Đại học Đồng Tháp",
    "country": "Vietnam",
    "impactRank": 3138,
    "opennessRank": 5974,
    "excellenceRank": 20592,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 50,
    "worldRank": 5457,
    "name": "University of Transport Technology / Trường Đại học Công nghệ giao thông vận tải",
    "country": "Vietnam",
    "impactRank": 12404,
    "opennessRank": 6362,
    "excellenceRank": 3065,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 51,
    "worldRank": 5644,
    "name": "University of Transport and Communications / Trường Đại học Giao thông Vận tải",
    "country": "Vietnam",
    "impactRank": 7970,
    "opennessRank": 3696,
    "excellenceRank": 6154,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 52,
    "worldRank": 5739,
    "name": "Hung Yen University of Technology and Education / Trường Đại Học Sư Phạm Kỹ Thuật Hưng Yên",
    "country": "Vietnam",
    "impactRank": 11644,
    "opennessRank": 4810,
    "excellenceRank": 4169,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 53,
    "worldRank": 5791,
    "name": "Ho Chi Minh City Medicine and Pharmacy University / Đại học Y Dược Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 12498,
    "opennessRank": 25974,
    "excellenceRank": 2663,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 54,
    "worldRank": 5944,
    "name": "Thai Nguyen University / Đại học Thái Nguyên Thai Nguyen",
    "country": "Vietnam",
    "impactRank": 5355,
    "opennessRank": 7343,
    "excellenceRank": 6729,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 55,
    "worldRank": 6822,
    "name": "Vietnam Forestry University / Đại học Lâm nghiệp",
    "country": "Vietnam",
    "impactRank": 10912,
    "opennessRank": 6775,
    "excellenceRank": 4817,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 56,
    "worldRank": 6839,
    "name": "Hanoi Open University / Đại học Mở Hà Nội",
    "country": "Vietnam",
    "impactRank": 4104,
    "opennessRank": 11507,
    "excellenceRank": 23621,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 57,
    "worldRank": 6969,
    "name": "Ho Chi Minh City University of Foreign Languages and Information Technology / Đại học Dân lập Ngoại ngữ Tin học Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 7944,
    "opennessRank": 8242,
    "excellenceRank": 5936,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 58,
    "worldRank": 7124,
    "name": "Vietnamese-German University / Đại học Việt-Đức",
    "country": "Vietnam",
    "impactRank": 6552,
    "opennessRank": 5413,
    "excellenceRank": 29410,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 59,
    "worldRank": 7152,
    "name": "Dalat University / Đại học Đà Lạt",
    "country": "Vietnam",
    "impactRank": 8930,
    "opennessRank": 4414,
    "excellenceRank": 6721,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 60,
    "worldRank": 7153,
    "name": "VinUniversity",
    "country": "Vietnam",
    "impactRank": 7678,
    "opennessRank": 3656,
    "excellenceRank": 17158,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 61,
    "worldRank": 7207,
    "name": "Dong A University / Trường Đại Học Đông Á",
    "country": "Vietnam",
    "impactRank": 6507,
    "opennessRank": 5760,
    "excellenceRank": 19378,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 62,
    "worldRank": 7294,
    "name": "Ho Chi Minh City University of Education / Trường Đại học Sư phạm Thành phố HCM",
    "country": "Vietnam",
    "impactRank": 10221,
    "opennessRank": 27092,
    "excellenceRank": 4870,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 63,
    "worldRank": 7333,
    "name": "Hong Duc University / Đại học Hồng Đức",
    "country": "Vietnam",
    "impactRank": 10422,
    "opennessRank": 6962,
    "excellenceRank": 5352,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 64,
    "worldRank": 7708,
    "name": "Vietnam Academy of Social Sciences / Viện Khoa học Xã hội Việt Nam",
    "country": "Vietnam",
    "impactRank": 5362,
    "opennessRank": 16001,
    "excellenceRank": 18900,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 65,
    "worldRank": 7858,
    "name": "Nha Trang University / Đại học Nha Trang",
    "country": "Vietnam",
    "impactRank": 8398,
    "opennessRank": 4140,
    "excellenceRank": 15711,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 66,
    "worldRank": 8045,
    "name": "Dong Nai University of Technology / Đại Học Công Nghệ Đồng Nai",
    "country": "Vietnam",
    "impactRank": 7329,
    "opennessRank": 6356,
    "excellenceRank": 27543,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 67,
    "worldRank": 8059,
    "name": "Hoa Sen University / Đại học Hoa Sen HSU",
    "country": "Vietnam",
    "impactRank": 5855,
    "opennessRank": 22501,
    "excellenceRank": 21090,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 68,
    "worldRank": 8128,
    "name": "Vietnam Maritime University / Đại học Hàng hải",
    "country": "Vietnam",
    "impactRank": 5968,
    "opennessRank": 16329,
    "excellenceRank": 19246,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 69,
    "worldRank": 8308,
    "name": "Le Quy Don Technical University / Học viện Kỹ thuật Quân sự Việt Nam",
    "country": "Vietnam",
    "impactRank": 19880,
    "opennessRank": 2977,
    "excellenceRank": 2605,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 70,
    "worldRank": 8534,
    "name": "Saigon University / Trường Đại học Sài Gòn",
    "country": "Vietnam",
    "impactRank": 8565,
    "opennessRank": 5393,
    "excellenceRank": 29616,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 71,
    "worldRank": 8540,
    "name": "Thang Long University / Đại học Thăng Long",
    "country": "Vietnam",
    "impactRank": 11770,
    "opennessRank": 10843,
    "excellenceRank": 4978,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 72,
    "worldRank": 9010,
    "name": "Hanoi University of Social Sciences and Humanities / Trường Đại học Xã hội và Nhân văn ĐHQGHN",
    "country": "Vietnam",
    "impactRank": 11242,
    "opennessRank": 27798,
    "excellenceRank": 5493,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 73,
    "worldRank": 9319,
    "name": "University of Science and Technology of Hanoi USTH Vietnam France University",
    "country": "Vietnam",
    "impactRank": 10215,
    "opennessRank": 4346,
    "excellenceRank": 18633,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 74,
    "worldRank": 9337,
    "name": "PACE Institute of Leadership and Management",
    "country": "Vietnam",
    "impactRank": 7572,
    "opennessRank": 31500,
    "excellenceRank": 14262,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 75,
    "worldRank": 9452,
    "name": "Thai Nguyen University of Education",
    "country": "Vietnam",
    "impactRank": 10311,
    "opennessRank": 4564,
    "excellenceRank": 11104,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 76,
    "worldRank": 9688,
    "name": "Ho Chi Minh City University of Economics and Finance UEF / Đại học Kinh Tế Tài Chính TPHCM UEF",
    "country": "Vietnam",
    "impactRank": 9269,
    "opennessRank": 6744,
    "excellenceRank": 29264,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 77,
    "worldRank": 9782,
    "name": "Hanoi University of Law / Trường Đại học Luật Hà Nội",
    "country": "Vietnam",
    "impactRank": 8120,
    "opennessRank": 31510,
    "excellenceRank": 31815,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 78,
    "worldRank": 9825,
    "name": "Banking Academy of Vietnam / Học viện Ngân hàng Việt Nam",
    "country": "Vietnam",
    "impactRank": 8196,
    "opennessRank": 30674,
    "excellenceRank": 28490,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 79,
    "worldRank": 9878,
    "name": "Hai Phong University / Đại học Hải Phòng",
    "country": "Vietnam",
    "impactRank": 8372,
    "opennessRank": 15572,
    "excellenceRank": 9946,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 80,
    "worldRank": 9974,
    "name": "Tay Bac University / Đại học Tây Bắc",
    "country": "Vietnam",
    "impactRank": 8449,
    "opennessRank": 27679,
    "excellenceRank": 8840,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 81,
    "worldRank": 9985,
    "name": "Hai Phong Private University / Trường Đại Học Dân Lập Hải Phòng",
    "country": "Vietnam",
    "impactRank": 8447,
    "opennessRank": 11111,
    "excellenceRank": 15032,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 82,
    "worldRank": 10130,
    "name": "Lac Hong University / Trường Đại học Lạc Hồng",
    "country": "Vietnam",
    "impactRank": 9222,
    "opennessRank": 7998,
    "excellenceRank": 7939,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 83,
    "worldRank": 10176,
    "name": "University of Languages and International Studies / Trường Đại học Ngoại ngữ",
    "country": "Vietnam",
    "impactRank": 12600,
    "opennessRank": 18617,
    "excellenceRank": 5590,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 84,
    "worldRank": 10315,
    "name": "Fulbright University Vietnam / Đại học Fulbright Việt Nam",
    "country": "Vietnam",
    "impactRank": 9792,
    "opennessRank": 7338,
    "excellenceRank": 16957,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 85,
    "worldRank": 10374,
    "name": "Academy of Finance / Học viện Tài chính Kế toán",
    "country": "Vietnam",
    "impactRank": 8968,
    "opennessRank": 17052,
    "excellenceRank": 8222,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 86,
    "worldRank": 10435,
    "name": "Ho Chi Minh City University of Law / Trường Đại Học Luật Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 9142,
    "opennessRank": 8749,
    "excellenceRank": 14026,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 87,
    "worldRank": 10633,
    "name": "Vietnam University of Commerce / Đại học Thương mại",
    "country": "Vietnam",
    "impactRank": 10470,
    "opennessRank": 6801,
    "excellenceRank": 18954,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 88,
    "worldRank": 10818,
    "name": "Thai Nguyen University of Sciences in Vietnam",
    "country": "Vietnam",
    "impactRank": 11667,
    "opennessRank": 5236,
    "excellenceRank": 10285,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 89,
    "worldRank": 10890,
    "name": "Diplomatic Academy of Vietnam / Học viện Ngoại giao Việt Nam",
    "country": "Vietnam",
    "impactRank": 9555,
    "opennessRank": 20103,
    "excellenceRank": 16577,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 90,
    "worldRank": 10928,
    "name": "Ho Chi Minh City University of Transportation / Trường Đại học Giao Thông Vận Tải Thành phố Hồ Chí Minh",
    "country": "Vietnam",
    "impactRank": 12155,
    "opennessRank": 4520,
    "excellenceRank": 27437,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 91,
    "worldRank": 11184,
    "name": "Hue College of Medicine / Trường Đại học Y khoa Huế",
    "country": "Vietnam",
    "impactRank": 11826,
    "opennessRank": 5753,
    "excellenceRank": 14614,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 92,
    "worldRank": 11190,
    "name": "Cần Thơ University of Technology / Đại Học Kỹ Thuật- Công Nghệ Cần Thơ",
    "country": "Vietnam",
    "impactRank": 10138,
    "opennessRank": 8659,
    "excellenceRank": 18046,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 93,
    "worldRank": 11429,
    "name": "Hanoi University of Pharmacy / Trường Đại học Dược Hà Nội",
    "country": "Vietnam",
    "impactRank": 11464,
    "opennessRank": 6792,
    "excellenceRank": 29939,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 94,
    "worldRank": 11464,
    "name": "Dai Nam University",
    "country": "Vietnam",
    "impactRank": 12711,
    "opennessRank": 4720,
    "excellenceRank": 27590,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 95,
    "worldRank": 11513,
    "name": "Hanoi University of Business and Technology / Đại học Kinh Doanh và Công Nghệ Hà Nội HUBT",
    "country": "Vietnam",
    "impactRank": 10358,
    "opennessRank": 16424,
    "excellenceRank": 16223,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 96,
    "worldRank": 11515,
    "name": "British University Vietnam",
    "country": "Vietnam",
    "impactRank": 10325,
    "opennessRank": 22707,
    "excellenceRank": 20501,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 97,
    "worldRank": 11520,
    "name": "Hong Bang International University / Trường Đại học Quốc tế Hồng Bàng",
    "country": "Vietnam",
    "impactRank": 10373,
    "opennessRank": 28682,
    "excellenceRank": 11518,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 98,
    "worldRank": 11583,
    "name": "Hanoi Architectural University / Đại học Kiến trúc Hà Nội",
    "country": "Vietnam",
    "impactRank": 10480,
    "opennessRank": 18093,
    "excellenceRank": 10466,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 99,
    "worldRank": 11602,
    "name": "Saigon Institute of Technology SaigonTech",
    "country": "Vietnam",
    "impactRank": 10469,
    "opennessRank": 12347,
    "excellenceRank": 18925,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  },
  {
    "rank": 100,
    "worldRank": 11649,
    "name": "Hung Vuong University / Đại học Hùng Vương Phú Thọ",
    "country": "Vietnam",
    "impactRank": 14049,
    "opennessRank": 21370,
    "excellenceRank": 5777,
    "sourceUrl": "https://www.webometrics.org/vietnam"
  }
];
